name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v0.1.4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DHOST }}
          username: ${{ secrets.DUSER }}
          password: ${{ secrets.DPASSWORD }}
          source: "y2x.cmd"
          target:
            ./
