name: deploy
run-name: Deploy to hiu by @${{ github.actor }}
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:

jobs:
  # This workflow contains a single job called "build"
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: execute migrations
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://www.d0nald.de/slack.php
