name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - uses: actions/checkout@v3 
      - run: ls -la
      - run: sshpass -p ${{ secrets.DPASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.DUSER }}@${{ secrets.DHOST }}:/.env.local.php .env.local.php
      - run: ls -la
      - uses: php-actions/composer@v3
      - run: ls -la
      - run: echo 'hi' > tut.txt
      - run: ls -la
      - run: "sshpass -p ${{ secrets.DPASSWORD }} scp tut.txt ${{ secrets.DUSER }}@${{ secrets.DHOST }}:"
     
