name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # - run: scp
      - run: sshpass -p ${{ secrets.DPASSWORD }} scp -r ${{ secrets.DUSER }}@${{ secrets.DHOST }}:/.env.local.php /.env.local.php
      - run: ls
