name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.DHOST }}
          username: ${{ secrets.DUSER }}
          insecure_password: ${{ secrets.DPASSWORD }}
          fingerprint: ${{ secrets.DFINGERPRINT }}
          source: test.txt
          target: test.txt
      - run: cat test.txt
