name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install lftp
      - run: lftp -e "mirror -R . testDeploy" -u ${{ secrets.DUSER }},${{ secrets.DPASSWORD }} ${{ secrets.DHOST }}
#      - uses: actions/checkout@v3
#      - run: sshpass -p ${{ secrets.DPASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.DUSER }}@${{ secrets.DHOST }}:/.env.local.php .env.local.php
#      - uses: php-actions/composer@v3
#      - run: "sshpass -p ${{ secrets.DPASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* ${{ secrets.DUSER }}@${{ secrets.DHOST }}:testDeploy/"
     
